name: ci-nullplatform
env:
  NULLPLATFORM_API_KEY: ${{ secrets.NULLPLATFORM_API_KEY }}
on:
  push:
    branches:
      - main
      - master
      - fix/runner-authorization
permissions:
  id-token: write
  contents: read
  packages: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install nullplatform cli
        run: curl https://cli.nullplatform.com/install.sh | sh
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start nullplatform CI
        run: np build start
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build AMD asset
        run: docker buildx build --platform linux/amd64 --build-arg linux-x64  -t amd --load .
      - name: Build ARM asset
        run: docker buildx build --platform linux/arm64 --build-arg linux-arm64 -t arm --load .
      - name: Push AMD asset
        run: np asset push --type docker-image --source amd --name runner-linux-amd64
      - name: Push ARM asset
        run: np asset push --type docker-image --source arm --name runner-linux-arm64
      - name: End nullplatform CI
        if: ${{ always() }}
        run: np build update --status ${{ contains(fromJSON('["failure", "cancelled"]'), job.status) && 'failed' || 'successful' }}