name: ci-nullplatform
on:
  push:
    branches:
      - master
      - main
permissions:
  id-token: write
  contents: read
  packages: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Start Nullplatform CI
        id: setup-ci
        uses: nullplatform/github-action-setup-ci@v1
        with:
          api-key: ${{ secrets.NULLPLATFORM_API_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get build parameters
        id: get-build-parameters
        uses: nullplatform/github-action-secrets-and-variables@v1
        with:
          application-id: ${{ steps.setup-ci.outputs.application-id }}
      - name: Build asset for ${{ steps.setup-ci.outputs.application-name }}
        id: build-asset
        uses: nullplatform/github-action-asset-build@v1
        with:
          command: docker/buildx
          arguments: build --build-arg VERSION=${{ vars.VERSION }} --build-arg ARCH=${{ vars.ARCH }}
          options: --platform ${{env.PLATFORMS}} -t main .
      - name: Push asset for ${{ steps.setup-ci.outputs.application-name }}
        id: push-asset
        uses: nullplatform/github-action-asset-push@v1
        with:
          build-id: ${{ steps.setup-ci.outputs.build-id }}
          type: docker-image
      - name: End Nullplatform CI
        if: ${{ always() }}
        id: end-setup-ci
        uses: nullplatform/github-action-setup-ci@v1
        with:
          build-id: ${{ steps.setup-ci.outputs.build-id }}
          status: ${{ contains(fromJSON('["failure", "cancelled"]'), job.status) && 'failed' || 'successful' }}
